#! /bin/bash
set -e
set -x 
sudo apt-get update
sudo apt-get install --yes git 
sudo apt-get install --yes curl 
sudo apt-get install --yes ack 
sudo apt-get install --yes zsh 
sudo apt-get install --yes vim
chsh -s /bin/zsh vagrant 
