#! /bin/bash
set -e
set -x 
sudo apt-get update
sudo apt-get install --yes git 
sudo apt-get install --yes curl 
sudo apt-get install --yes zsh 
sudo apt-get install --yes vim

if grep ubuntu /etc/passwd
then
    chsh -s /bin/zsh ubuntu
else
    chsh -s /bin/zsh vagrant
fi;
